### ISSUE TITLE
Bug in latest Android Chrome while trying TouchList objects demo

### ISSUE THREAD

**Issue by erichlof** [patrickhlauke/touch#17]
Hi Patrick, 
First, thank you very much for this comprehensive guide to touch events and API - I am learning a lot from your excellent demos.

While trying your TouchList objects demo on my Samsung Galaxy S7 edge, I noticed choppy behavior that wasn't there before. Touch and hold 'Test Button' with one finger, then with a second finger (maybe with your other hand for ease), touch outside the blue Test button and try to drag the new 2nd touchpoint circles around the screen.  At least on my device, the second touch's move events are firing very slowly which leads to choppy animation of the second touch circles.

 I have my own project [Here](https://github.com/erichlof/THREE.js-PathTracing-Renderer)  which includes support for mobile devices on Chrome.  I have simple fly controls , (up,down,left,right arrow buttons) and the ability to swipe the screen with a finger to rotate the 1st-person camera.  A couple of months back before this bug appeared, users could hold down the fly forward button for example with one finger, then swipe with another finger to rotate the camera angle at the same time: no problem.   But now, when holding a fly direction button, and then attempting to swipe with a 2nd finger, the swiping motion (or 'touchmove') is super choppy.

I'm confused as to whether this is a Chrome bug, or bad code on my part that 'used to just work' but now doesn't because I need to somehow code it the right way to be in line with the current Chrome implementation.  This is what brought me to your website where I noticed similar behavior.
Could you please confirm if you can reproduce this behavior on your test devices? If so, I will gladly file a bug report over at Chromium.  If not, could you please point me in the right direction, or demo, of how I should be handling multitouch move gestures with buttons involved?

I would greatly appreciate it.
Thank you,
-Erich

**Comment by patrickhlauke** [comment]
super late reply, but only stumbled across this again while having a look at my repo after a long hiatus...
i don't see any weird behaviour in my test devices, so might be/have been a browser-specific issue. possibly adding something like `touch-action: none;` to whatever container you had could help alleviate/solve this.

**Comment by erichlof** [comment]
@patrickhlauke 
Hi Patrick, thank you - yes the 'touch-action: none' indeed does the trick!  :)
