### ISSUE TITLE
Firefox fails test for Touchscreen

### ISSUE THREAD

**Issue by richardbushell** [patrickhlauke/touch#19]
Hi Patrick

Firefox fails the TEST for TOUCHSCREEN (on my Touchscreen Laptop) because Firefox returns:
navigator.maxTouchPoints = 0   (and not >0)

I don't know if that is a browser bug? But it does point out an error in your LOGIC here:
https://patrickhlauke.github.io/touch/touchscreen-detection/

Because the >0 test fails for navigator.maxTouchPoints, the function returns FALSE.

Shouldn't the >0 test be included in ONE single test, so:
if (window.PointerEvent && ('maxTouchPoints' in navigator) && (navigator.maxTouchPoints > 0) ) {...}

That way the ELSE clause would be actioned, and those tests would PASS for Touchscreen anyway, hence returning TRUE.

**Comment by patrickhlauke** [comment]
interesting. the logic is sound. if a browser properly supports pointer events, it should also expose the correct number of touch points. my script doesn't account for browser bugs, which is the case here for Firefox. feel free to adapt it to your needs, but i'd rather not add code to work around bugs.
