### ISSUE TITLE
Touch events should allow for device-pixel accuracy

### ISSUE THREAD

**Issue by roman-rr** [patrickhlauke/touch#25]
@patrickhlauke

Hello Patrick. Firstly, i wanna say big thanks for you works. 

I don't find where i can ask regarding issue mentioned as [Touch events should allow for device-pixel accuracy](https://bugs.webkit.org/show_bug.cgi?id=133180)

Can you advice any alternative for using in Safari more precision touchmove event, maybe some kind of js polyfill ? Or maybe you know when float will change long type ?

**Comment by patrickhlauke** [comment]
it's a bug/shortcoming of the browser (Safari). there's no workaround possible (as there's nowhere else JavaScript could get the coordinates)...you'll need to wait for Apple to fix it at their end I'm afraid.
