### ISSUE TITLE
Question regarding chain of events in Chrome on iOS

### ISSUE THREAD

**Issue by avnermosh** [patrickhlauke/touch#29]
Hello,
I'm testing the chain of touch events, on iOS 14.01 (iPad Pro 12.9")
and I find some differences between Safari, and Chrome.
In Safari, the chain of events is similar to what I see in the table in https://patrickhlauke.github.io/touch/tests/results/
e.g. for the case of iOS 13.1:
For example, for the first and second tap, the event starts with "pointerover", propagates to "touchstart", and evebventually to "click"

But for Chrome, I see diffeent behavior:
the second tap does not start with "pointerover", does not propagate via "touchstart", and gets to "click" quickly from mouse events.
Can you explain this behavior?

I'm asking because I see this behaviour also in my webapp where there are more click events than "touchstart" events.
This is causing side-effects of zooming-in which is default browser behaviour on iOS.
Suggestions on the web to deal with this are e.g. (this) https://medium.com/building-blocks/code-snippet-4accfa29b75d
which apply preventDefault in the touchstart, or touchend, which according to (here) https://w3c.github.io/touch-events/#h-note5
should disable the "click" event.
But because of this behavior, there are fewer "touchstart", "touchend" events compared to "click" events
and the commands to preventDefault/stopPropagation within touchstart/touchend are not effective.
![image](https://user-images.githubusercontent.com/26158466/120603441-e53daa80-c400-11eb-9b1e-0c63ad4f8e43.png)

**Comment by patrickhlauke** [comment]
don't have an ipad handy at the moment, but certainly on iphone i get exactly the expected event sequence in chrome as in safari (since it uses safari under the hood, like all iOS/iPadOS browsers) when trying https://patrickhlauke.github.io/touch/tests/event-listener.html

![Photo 03-06-2021, 21 35 08](https://user-images.githubusercontent.com/895831/120709516-da445200-c4b4-11eb-96fe-d96d4130c47f.png)

so you must have something else going on in your test/app that's somehow influencing events that are being fired.

for preventing double-tap-to-zoom behaviour, i'd try and see if Safari has implemented the `touch-action:manipulation` CSS property https://w3c.github.io/pointerevents/#details-of-touch-action-values

**Comment by avnermosh** [comment]
The results you posted here - are they for iOS 14.x, and Chrome 90.x / 91.x?

> so you must have something else going on in your test/app that's somehow influencing events that are being fired.  

The results that I posted are from the test in https://patrickhlauke.github.io/touch/tests/event-listener.html
They have nothing to do with my test/app.
I repeated the test and got exactly the same results (for Chrome 90.0.4430.216 - iOS 14.01)

Next, I upgraded to the latest available as of this time:
- iOS - 14.6
- Chrome - 91.0.4472.80
I repeated the test, and I get the same results (snapshot2).
I made sure to reboot the device and Chrome is the only active app.
(with Safari, I get the same results to what you posted)

![image](https://user-images.githubusercontent.com/26158466/120740570-49677980-c4a8-11eb-9d4e-4404b42c2e04.png)

**Comment by avnermosh** [comment]
I checked on 2 more iOS devices and I see the same results:
- iPhone 8 Plus  - Chrome 90.0.4430.216 iOS 14.4.2
- iPhone 11 - Chrome 91.0.4472.80 iOS 14.4.2

They both also show the same behaviour
- ok for Safari, (and Firefox on iPhone 8)
- **NOT OK for Chrome**

![iPhone8](https://user-images.githubusercontent.com/26158466/120752316-598a5380-c4be-11eb-845b-121f8182b5b2.jpg)
![iPhone11](https://user-images.githubusercontent.com/26158466/120752925-475ce500-c4bf-11eb-84d5-c306e0656414.jpg)

**Comment by patrickhlauke** [comment]
to be clear, my "2nd tap" is about "you tap it...wait a second...then tap again". it's not testing double-tap gestures.

**Comment by patrickhlauke** [comment]
again, at that point, if you want to disable double-tap, try adding `touch-action:manipulation`. and noting that Safari (and more specifically, the WKWebView component that is used by non-Safari browsers) is known to behave badly with certain touch gesture handling etc. it *may* be a bug in how Chrome/iOS has implemented it, but that's probably something to file in Google's issue tracker.

**Comment by patrickhlauke** [comment]
video: https://www.youtube.com/watch?v=WYO-slYY-1k

will ping some Google folks...

**Comment by patrickhlauke** [comment]
https://lists.w3.org/Archives/Public/public-pointer-events/2021AprJun/0196.html

**Comment by avnermosh** [comment]
> again, at that point, if you want to disable double-tap, try adding touch-action:manipulation

Do you know if touch-action:manipulation can be added to any element upstream in the DOM tree?
Or does it have to be set to the target element?
I'm asking because I tried placing it up the DOM tree, and it did not work (zoom-in on double tap still kicks in) - but it also did not work when I placed in the target element (taking your note about the bad WKWebView behaviour)
(this is a off the topic, but I thought to use your expertise here :smile: )

---

Also, I found a new event that I was not aware of: _dblclick_
On double-click, this event is fired. This happens in Chrome on e.g. Linux but not on iOS

According to [mozilla](https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event):

> dblclick fires after two click events (and by extension, after two pairs of mousedown and mouseup events).

From this, I understand that by the time that _dblclick_ event fires, 2 clicks already happened, which already trigger the browser's default behaviour of zoom-in (i.e. too late to disable the zoom-in, e.g. using _preventDefault(), stopPropagation()_, in the _dblclick_ event listener).
I'm curious, why this event is not added to the eventListener in _report.js_ in your [touch test](https://patrickhlauke.github.io/touch/tests/event-listener.html)) ?

Thanks
