### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cvrebert** [patrickhlauke/touch#9]
There's no LICENSE file and I can't seem to find any other notice of what license is applicable (except for some vendored scripts+CSS).

**Comment by patrickhlauke** [comment]
Any suggestion what license you'd like to see here? I usually say that most of my stuff is CC-BY-NC, but i head use of CC is frowned upon for software...

**Comment by cvrebert** [comment]
Indeed, due to incompatibility with common FOSS licenses.

How firm of a requirement is the inclusion of NC-ish terms?

**Comment by patrickhlauke** [comment]
maybe not so much for the actual demos, but certainly the compiled test results it would be nice to get both an aknowledgement and avoid that somebody makes some form of commercial gain out of it. but to be honest, not too fussed...

**Comment by cvrebert** [comment]
You could put the demos+tests and the test results under different licenses.
e.g. MIT for the demos and CC-BY-NC for the test results.

**Comment by patrickhlauke** [comment]
Went for simple MIT for the lot...doubt anybody will become rich from my results ;)
